<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.40.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Schuly.Plugin.Abstractions/Schuly.Plugin.Abstractions.csproj" />
  </ItemGroup>

</Project>
